name = "deadlight-boo"
main = "src/index.js"
compatibility_date = "2023-10-20"

[[routes]]
pattern = "*blog.deadlight.boo/*"
zone_id = "792d194e8484b6f03e8b3d767d0bfe1a"

[[routes]]
pattern = "blog.deadlight.boo/*"
zone_id = "792d194e8484b6f03e8b3d767d0bfe1a" 

[observability.logs]
enabled = true

[build]
command = "npm install"

[vars]
JWT_SECRET = "development-secret-key-please-change-in-production"

[[d1_databases]]
binding = "DB"
database_name = "blog_content_new"
database_id = "05792bea-8178-4509-8927-bc79bfeb8340"
